"""Stable schema contracts for proactive wake services."""

from assistant_agent.schemas.proactive_wake import (
    AttentionDecision,
    AttentionOutcome,
    DeliveryResult,
    DeliveryStatus,
    NotificationEnvelope,
    ProactiveWakeRunResult,
    QuietHours,
    Severity,
    WakeAttentionSpec,
    WakeConditionMode,
    WakeConditionSpec,
    WakeDecision,
    WakeDecisionOutcome,
    WakeEvidence,
    WakeOwner,
    WakeProbeSpec,
    WakeRule,
    WakeRuleState,
    WakeRun,
    WakeRunStatus,
    WakeSignal,
    WakeSignalKind,
    WakeTriggerSpec,
)

__all__ = [
    "AttentionDecision",
    "AttentionOutcome",
    "DeliveryResult",
    "DeliveryStatus",
    "NotificationEnvelope",
    "ProactiveWakeRunResult",
    "QuietHours",
    "Severity",
    "WakeAttentionSpec",
    "WakeConditionMode",
    "WakeConditionSpec",
    "WakeDecision",
    "WakeDecisionOutcome",
    "WakeEvidence",
    "WakeOwner",
    "WakeProbeSpec",
    "WakeRule",
    "WakeRuleState",
    "WakeRun",
    "WakeRunStatus",
    "WakeSignal",
    "WakeSignalKind",
    "WakeTriggerSpec",
]
