"""Compatibility mappings for the legacy intent/action planning path."""

from assistant_agent.tools.ids import (
    CALENDAR_CREATE_TOOL_NAME,
    CALENDAR_SEARCH_TOOL_NAME,
    CONTACTS_SEARCH_TOOL_NAME,
    IMAGE_GENERATION_CAPABILITY,
    IMAGE_GENERATION_TOOL_NAME,
    IMAGE_UNDERSTANDING_CAPABILITY,
    MEDIA_INSPECT_TOOL_NAME,
    PYTHON_INTERPRETER_TOOL_NAME,
    SHOPPING_SEARCH_CAPABILITY,
    SHOPPING_SEARCH_TOOL_NAME,
    VIDEO_UNDERSTANDING_CAPABILITY,
    VISUAL_IMAGE_SEARCH_CAPABILITY,
    VISUAL_IMAGE_SEARCH_TOOL_NAME,
    WEATHER_TOOL_NAME,
    WEB_FETCH_CAPABILITY,
    WEB_FETCH_TOOL_NAME,
    WEB_SEARCH_CAPABILITY,
    WEB_SEARCH_TOOL_NAME,
)


_TOOL_BY_CAPABILITY = {
    IMAGE_UNDERSTANDING_CAPABILITY: MEDIA_INSPECT_TOOL_NAME,
    VIDEO_UNDERSTANDING_CAPABILITY: MEDIA_INSPECT_TOOL_NAME,
    IMAGE_GENERATION_CAPABILITY: IMAGE_GENERATION_TOOL_NAME,
    WEB_SEARCH_CAPABILITY: WEB_SEARCH_TOOL_NAME,
    WEB_FETCH_CAPABILITY: WEB_FETCH_TOOL_NAME,
    VISUAL_IMAGE_SEARCH_CAPABILITY: VISUAL_IMAGE_SEARCH_TOOL_NAME,
    SHOPPING_SEARCH_CAPABILITY: SHOPPING_SEARCH_TOOL_NAME,
    WEATHER_TOOL_NAME: WEATHER_TOOL_NAME,
    CALENDAR_SEARCH_TOOL_NAME: CALENDAR_SEARCH_TOOL_NAME,
    CALENDAR_CREATE_TOOL_NAME: CALENDAR_CREATE_TOOL_NAME,
    CONTACTS_SEARCH_TOOL_NAME: CONTACTS_SEARCH_TOOL_NAME,
    PYTHON_INTERPRETER_TOOL_NAME: PYTHON_INTERPRETER_TOOL_NAME,
}
_CAPABILITY_BY_TOOL = {
    tool_name: capability
    for capability, tool_name in _TOOL_BY_CAPABILITY.items()
    if capability != VIDEO_UNDERSTANDING_CAPABILITY
}
_ACTION_BY_CAPABILITY = {
    IMAGE_UNDERSTANDING_CAPABILITY: "understand_image",
    VIDEO_UNDERSTANDING_CAPABILITY: "understand_video",
    IMAGE_GENERATION_CAPABILITY: "generate_image",
    WEB_SEARCH_CAPABILITY: "search_web",
    WEB_FETCH_CAPABILITY: "fetch_web",
    VISUAL_IMAGE_SEARCH_CAPABILITY: "search_image_by_image",
    SHOPPING_SEARCH_CAPABILITY: SHOPPING_SEARCH_CAPABILITY,
}
_CAPABILITY_BY_ACTION = {
    action: capability for capability, action in _ACTION_BY_CAPABILITY.items()
}
_CAPABILITY_BY_ACTION["read_url"] = WEB_FETCH_CAPABILITY


def canonical_tool_for_capability(capability: str) -> str | None:
    return _TOOL_BY_CAPABILITY.get(capability)


def canonical_capability_for_tool(tool_name: str) -> str | None:
    return _CAPABILITY_BY_TOOL.get(tool_name)


def canonical_action_for_capability(capability: str) -> str | None:
    return _ACTION_BY_CAPABILITY.get(capability)


def canonical_capability_for_action(action: str) -> str | None:
    return _CAPABILITY_BY_ACTION.get(action)
