"""Application configuration loading during the temporary migration."""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING

from .models import (
    AppConfig,
    ChatConfig,
    ImageGenerationConfig,
    LodgingConfig,
    MediaConfig,
    MemoryConfig,
    RuntimeConfig,
    SearchConfig,
    ShoppingConfig,
    ToolConfig,
    VisionConfig,
)

if TYPE_CHECKING:
    from . import ProviderConfig


def load_app_config(env: Mapping[str, str] | None = None) -> AppConfig:
    """Load nested configuration from the legacy parser during migration."""

    from assistant_agent.config import ProviderConfig

    return _app_config_from_legacy(ProviderConfig.from_env(env))


def _app_config_from_legacy(legacy: ProviderConfig) -> AppConfig:
    return AppConfig(
        provider_mode=legacy.provider_mode,
        runtime=RuntimeConfig(
            current_location=legacy.current_location,
            agent_service_text_turn_timeout_seconds=(
                legacy.agent_service_text_turn_timeout_seconds
            ),
            langgraph_checkpointer_backend=legacy.langgraph_checkpointer_backend,
            langgraph_checkpoint_path=legacy.langgraph_checkpoint_path,
        ),
        chat=ChatConfig(
            openai_api_key=legacy.openai_api_key,
            qwen_api_key=legacy.qwen_api_key,
            dashscope_api_key=legacy.dashscope_api_key,
            ark_api_key=legacy.ark_api_key,
            chat_provider=legacy.chat_provider,
            chat_api_key=legacy.chat_api_key,
            chat_base_url=legacy.chat_base_url,
            chat_model=legacy.chat_model,
            chat_adapter_kind=legacy.chat_adapter_kind,
            chat_stream=legacy.chat_stream,
            native_provider_streaming=legacy.native_provider_streaming,
            chat_timeout_seconds=legacy.chat_timeout_seconds,
            deep_research_chat_max_tokens=legacy.deep_research_chat_max_tokens,
            context_compactor_mode=legacy.context_compactor_mode,
            context_tokenizer_path=legacy.context_tokenizer_path,
            context_input_token_limit=legacy.context_input_token_limit,
            context_compaction_trigger_ratio=legacy.context_compaction_trigger_ratio,
            context_compaction_target_ratio=legacy.context_compaction_target_ratio,
            context_compaction_hard_ratio=legacy.context_compaction_hard_ratio,
            context_compaction_safety_margin_tokens=(
                legacy.context_compaction_safety_margin_tokens
            ),
            context_summary_max_tokens=legacy.context_summary_max_tokens,
            qwen_chat_enable_thinking=legacy.qwen_chat_enable_thinking,
            qwen_chat_enable_search=legacy.qwen_chat_enable_search,
            qwen_chat_api_protocol=legacy.qwen_chat_api_protocol,
            openai_chat_base_url=legacy.openai_chat_base_url,
            openai_chat_model=legacy.openai_chat_model,
            qwen_chat_base_url=legacy.qwen_chat_base_url,
            qwen_chat_workspace_id=legacy.qwen_chat_workspace_id,
            qwen_chat_model=legacy.qwen_chat_model,
            deepseek_api_key=legacy.deepseek_api_key,
            deepseek_chat_base_url=legacy.deepseek_chat_base_url,
            deepseek_chat_model=legacy.deepseek_chat_model,
            ark_chat_api_key=legacy.ark_chat_api_key,
            ark_chat_base_url=legacy.ark_chat_base_url,
            ark_chat_model=legacy.ark_chat_model,
            local_chat_base_url=legacy.local_chat_base_url,
            local_chat_model=legacy.local_chat_model,
        ),
        vision=VisionConfig(
            qwen_vision_api_key=legacy.qwen_vision_api_key,
            qwen_realtime_vision_api_key=legacy.qwen_realtime_vision_api_key,
            ark_vision_api_key=legacy.ark_vision_api_key,
            seed_api_key=legacy.seed_api_key,
            vision_provider=legacy.vision_provider,
            vision_api_key=legacy.vision_api_key,
            vision_base_url=legacy.vision_base_url,
            vision_model=legacy.vision_model,
            vision_adapter_kind=legacy.vision_adapter_kind,
            vision_embedding_provider=legacy.vision_embedding_provider,
            embedding_provider=legacy.embedding_provider,
            vision_embedding_api_key=legacy.vision_embedding_api_key,
            vision_embedding_base_url=legacy.vision_embedding_base_url,
            vision_embedding_model=legacy.vision_embedding_model,
            vision_embedding_dimension=legacy.vision_embedding_dimension,
            vision_embedding_timeout_seconds=legacy.vision_embedding_timeout_seconds,
            siglip2_vision_model_dir=legacy.siglip2_vision_model_dir,
            siglip2_cuda_device_id=legacy.siglip2_cuda_device_id,
            siglip2_model_dir=legacy.siglip2_model_dir,
            embedding_cuda_device_id=legacy.embedding_cuda_device_id,
            keyframe_max_interval_seconds=legacy.keyframe_max_interval_seconds,
            keyframe_semantic_threshold=legacy.keyframe_semantic_threshold,
            visual_memory_candidate_similarity=(
                legacy.visual_memory_candidate_similarity
            ),
            visual_memory_confirmed_similarity=(
                legacy.visual_memory_confirmed_similarity
            ),
            visual_memory_qdrant_url=legacy.visual_memory_qdrant_url,
            visual_memory_qdrant_collection=legacy.visual_memory_qdrant_collection,
            visual_memory_qdrant_timeout_seconds=(
                legacy.visual_memory_qdrant_timeout_seconds
            ),
            visual_memory_dense_model_cache_dir=(
                legacy.visual_memory_dense_model_cache_dir
            ),
            visual_memory_result_limit=legacy.visual_memory_result_limit,
            visual_reminder_similarity_threshold=(
                legacy.visual_reminder_similarity_threshold
            ),
            visual_reminder_max_active=legacy.visual_reminder_max_active,
            visual_reminder_terminal_history_limit=(
                legacy.visual_reminder_terminal_history_limit
            ),
            openai_vision_base_url=legacy.openai_vision_base_url,
            openai_vision_model=legacy.openai_vision_model,
            qwen_vision_base_url=legacy.qwen_vision_base_url,
            qwen_vision_model=legacy.qwen_vision_model,
            qwen_realtime_vision_base_url=legacy.qwen_realtime_vision_base_url,
            qwen_realtime_vision_model=legacy.qwen_realtime_vision_model,
            qwen_realtime_vision_workspace_id=(
                legacy.qwen_realtime_vision_workspace_id
            ),
            qwen_realtime_vision_region=legacy.qwen_realtime_vision_region,
            ark_vision_base_url=legacy.ark_vision_base_url,
            ark_vision_model=legacy.ark_vision_model,
            seed_vision_base_url=legacy.seed_vision_base_url,
            seed_vision_model=legacy.seed_vision_model,
            visual_context_compactor_mode=legacy.visual_context_compactor_mode,
            visual_context_tokenizer_path=legacy.visual_context_tokenizer_path,
            visual_context_input_token_limit=legacy.visual_context_input_token_limit,
            visual_context_compaction_target_ratio=(
                legacy.visual_context_compaction_target_ratio
            ),
            visual_context_compaction_trigger_ratio=(
                legacy.visual_context_compaction_trigger_ratio
            ),
            visual_context_compaction_hard_ratio=(
                legacy.visual_context_compaction_hard_ratio
            ),
            visual_context_compaction_safety_margin_tokens=(
                legacy.visual_context_compaction_safety_margin_tokens
            ),
            visual_context_summary_max_tokens=(
                legacy.visual_context_summary_max_tokens
            ),
            visual_context_keep_recent_records=(
                legacy.visual_context_keep_recent_records
            ),
            visual_context_instruction_reserve_tokens=(
                legacy.visual_context_instruction_reserve_tokens
            ),
            visual_context_image_reserve_tokens=(
                legacy.visual_context_image_reserve_tokens
            ),
            visual_context_output_reserve_tokens=(
                legacy.visual_context_output_reserve_tokens
            ),
        ),
        memory=MemoryConfig(
            mem0_base_url=legacy.mem0_base_url,
            mem0_api_key=legacy.mem0_api_key,
            mem0_timeout_seconds=legacy.mem0_timeout_seconds,
            mem0_identity_namespace=legacy.mem0_identity_namespace,
            memory_backend=legacy.memory_backend,
            memory_commit_ledger_path=legacy.memory_commit_ledger_path,
            memory_extraction_delay_seconds=legacy.memory_extraction_delay_seconds,
            langmem_model=legacy.langmem_model,
            conversation_history_backend=legacy.conversation_history_backend,
            conversation_history_path=legacy.conversation_history_path,
            max_conversation_history_turns=legacy.max_conversation_history_turns,
            editable_context_enabled=legacy.editable_context_enabled,
            editable_context_root=legacy.editable_context_root,
            editable_context_user_id=legacy.editable_context_user_id,
        ),
        media=MediaConfig(
            proactive_message_delivery_timeout_seconds=(
                legacy.proactive_message_delivery_timeout_seconds
            ),
            proactive_delivery_store_path=legacy.proactive_delivery_store_path,
            proactive_delivery_ack_timeout_seconds=(
                legacy.proactive_delivery_ack_timeout_seconds
            ),
            proactive_delivery_lease_seconds=legacy.proactive_delivery_lease_seconds,
            proactive_delivery_presence_ttl_seconds=(
                legacy.proactive_delivery_presence_ttl_seconds
            ),
            proactive_delivery_poll_interval_seconds=(
                legacy.proactive_delivery_poll_interval_seconds
            ),
            remote_visual_memory_enabled=legacy.remote_visual_memory_enabled,
            remote_visual_memory_base_url=legacy.remote_visual_memory_base_url,
            remote_visual_memory_query_timeout_seconds=(
                legacy.remote_visual_memory_query_timeout_seconds
            ),
            remote_visual_memory_query_top_k=legacy.remote_visual_memory_query_top_k,
            remote_visual_memory_download_base_url=(
                legacy.remote_visual_memory_download_base_url
            ),
            remote_visual_memory_segment_seconds=(
                legacy.remote_visual_memory_segment_seconds
            ),
            remote_visual_memory_spool_root=legacy.remote_visual_memory_spool_root,
            remote_visual_memory_file_ttl_seconds=(
                legacy.remote_visual_memory_file_ttl_seconds
            ),
            remote_visual_memory_poll_interval_seconds=(
                legacy.remote_visual_memory_poll_interval_seconds
            ),
            artifact_base_url=legacy.artifact_base_url,
            td_gen_ip=legacy.td_gen_ip,
            td_gen_port=legacy.td_gen_port,
            public_ip=legacy.public_ip,
            public_port=legacy.public_port,
            image_to_3d_timeout_seconds=legacy.image_to_3d_timeout_seconds,
            video_understanding_timeout_seconds=(
                legacy.video_understanding_timeout_seconds
            ),
            max_video_bytes=legacy.max_video_bytes,
            max_video_seconds=legacy.max_video_seconds,
        ),
        tools=ToolConfig(
            local_file_access_root=legacy.local_file_access_root,
            durable_tasks_enabled=legacy.durable_tasks_enabled,
            image_generation=ImageGenerationConfig(
                qwen_image_api_key=legacy.qwen_image_api_key,
                ark_image_api_key=legacy.ark_image_api_key,
                comfyui_base_url=legacy.comfyui_base_url,
                image_generation_provider=legacy.image_generation_provider,
                image_generation_api_key=legacy.image_generation_api_key,
                image_generation_base_url=legacy.image_generation_base_url,
                image_generation_model=legacy.image_generation_model,
                image_generation_adapter_kind=legacy.image_generation_adapter_kind,
                openai_image_model=legacy.openai_image_model,
                qwen_image_base_url=legacy.qwen_image_base_url,
                qwen_image_model=legacy.qwen_image_model,
                qwen_image_default_size=legacy.qwen_image_default_size,
                ark_image_base_url=legacy.ark_image_base_url,
                ark_image_model=legacy.ark_image_model,
                ark_image_default_size=legacy.ark_image_default_size,
                ark_image_output_format=legacy.ark_image_output_format,
                local_image_base_url=legacy.local_image_base_url,
                local_image_model=legacy.local_image_model,
            ),
            search=SearchConfig(
                search_api_base_url=legacy.search_api_base_url,
                search_provider=legacy.search_provider,
                web_search_base_url=legacy.web_search_base_url,
                web_search_api_key=legacy.web_search_api_key,
                web_search_timeout_seconds=legacy.web_search_timeout_seconds,
                tavily_api_key=legacy.tavily_api_key,
                tavily_base_url=legacy.tavily_base_url,
                visual_image_search_provider=legacy.visual_image_search_provider,
                qwen_image_search_api_key=legacy.qwen_image_search_api_key,
                qwen_image_search_base_url=legacy.qwen_image_search_base_url,
                qwen_image_search_model=legacy.qwen_image_search_model,
                qwen_image_search_timeout_seconds=(
                    legacy.qwen_image_search_timeout_seconds
                ),
            ),
            shopping=ShoppingConfig(
                shopping_search_provider=legacy.shopping_search_provider,
                shopping_search_base_url=legacy.shopping_search_base_url,
                shopping_search_api_key=legacy.shopping_search_api_key,
                shopping_search_timeout_seconds=(
                    legacy.shopping_search_timeout_seconds
                ),
                shopping_compare_provider=legacy.shopping_compare_provider,
                shopping_compare_base_url=legacy.shopping_compare_base_url,
                shopping_compare_api_key=legacy.shopping_compare_api_key,
                shopping_compare_timeout_seconds=(
                    legacy.shopping_compare_timeout_seconds
                ),
                haodanku_api_key=legacy.haodanku_api_key,
                haodanku_base_url=legacy.haodanku_base_url,
                haodanku_timeout_seconds=legacy.haodanku_timeout_seconds,
                haodanku_enabled_platforms=legacy.haodanku_enabled_platforms,
                haodanku_taobao_pid=legacy.haodanku_taobao_pid,
                haodanku_taobao_authorized_name=(
                    legacy.haodanku_taobao_authorized_name
                ),
                haodanku_jd_sub_union_id=legacy.haodanku_jd_sub_union_id,
                haodanku_pdd_channel=legacy.haodanku_pdd_channel,
            ),
            lodging=LodgingConfig(
                lodging_provider=legacy.lodging_provider,
                flyai_cli_path=legacy.flyai_cli_path,
                flyai_api_key=legacy.flyai_api_key,
                flyai_timeout_seconds=legacy.flyai_timeout_seconds,
            ),
        ),
    )
